export const packages = [
  {
    slug: "date-night-helper",
    name: "Date Night Helper",
    baseTimeHours: 3,
    basePriceMin: 199,
    basePriceMax: 349,
    outcome: "Enjoy a stress-free night—plans handled, home reset after.",
    inclusions: [
      "Restaurant booking OR simple at-home setup",
      "Sitter coordination (we do not provide direct childcare)",
      "Ambiance: flowers/candles/music preset",
      "Quick post-evening reset (surfaces, dishes start)",
    ],
    limits: [
      "No childcare provided; coordination only",
      "No deep cleaning or cooking complex meals",
    ],
    image: "/images/packages/date-night.png",
  },
  {
    slug: "weekend-home-reset",
    name: "Weekend Home Reset",
    baseTimeHours: 3,
    basePriceMin: 179,
    basePriceMax: 299,
    outcome: "Start the weekend fresh with a tidy, organized home.",
    inclusions: [
      "Laundry folded and put away",
      "Kids’ areas reset and organized",
      "Kitchen/fridge quick refresh",
      "Bathrooms tidied (light reset)",
    ],
    limits: ["No deep cleaning", "No heavy lifting"],
    image: "/images/packages/weekend-reset.png",
  },
  {
    slug: "errand-blitz",
    name: "Errand Blitz",
    baseTimeHours: 2.5,
    basePriceMin: 99,
    basePriceMax: 199,
    outcome: "Groceries, pharmacy, returns, gifts—done in one run.",
    inclusions: [
      "Grocery shopping & drop-off",
      "Pharmacy / dry-clean / parcel returns",
      "Gift pickup/wrapping",
    ],
    limits: [
      "Mileage billed after 10 miles RT",
      "Purchases reimbursed at cost (+10% handling optional)",
    ],
    image: "/images/packages/errand-blitz.png",
  },
  {
    slug: "party-prep-tidy",
    name: "Party Prep & Tidy",
    baseTimeHours: 4,
    basePriceMin: 249,
    basePriceMax: 399,
    outcome: "Host without stress—setup, light serving, quick reset.",
    inclusions: [
      "Decor setup and delivery coordination",
      "Light serving / guest support",
      "Post-event surface reset",
    ],
    limits: ["No deep clean", "No catering beyond plating/serving"],
    image: "/images/packages/party-helper.png",
  },
  {
    slug: "travel-helper",
    name: "Travel Helper",
    baseTimeHours: 3,
    basePriceMin: 179,
    basePriceMax: 329,
    outcome: "Pack, depart, and return to a stocked home.",
    inclusions: [
      "Packing/unpacking assistance",
      "Home prep before departure",
      "Fridge restock for return",
      "Delivery/hold coordination",
    ],
    limits: ["No transporting minors", "No valuables inventory"],
    image: "/images/packages/travel.png",
  },
  {
    slug: "morning-launch",
    name: "Morning Launch (School)",
    baseTimeHours: 2,
    basePriceMin: 129,
    basePriceMax: 199,
    outcome: "Mornings run smooth—clothes, lunches, bags ready.",
    inclusions: [
      "Uniforms/clothes laid out",
      "Lunches prepped",
      "Bags organized, forms checked",
      "Quick kitchen reset",
    ],
    limits: ["No childcare", "No school transport"],
    image: "/images/packages/launch.png",
  },
  {
    slug: "new-baby-setup",
    name: "New Baby Setup",
    baseTimeHours: 3,
    basePriceMin: 199,
    basePriceMax: 329,
    outcome: "Non-medical nursery readiness and household prep.",
    inclusions: [
      "Nursery organization",
      "Bottle/diaper stations",
      "Grocery essentials + meal kit setup",
    ],
    limits: ["No medical care", "No babysitting"],
    image: "/images/packages/new-baby.webp",
  },
  {
    slug: "holiday-decor",
    name: "Holiday Decor (Inside)",
    baseTimeHours: 3.5,
    basePriceMin: 229,
    basePriceMax: 379,
    outcome: "Seasonal decor staged safely and neatly.",
    inclusions: [
      "Pull from storage & stage decor",
      "Interior ladder-safe setup",
      "Optional pack-down add-on",
    ],
    limits: ["No exterior ladders", "No roof work"],
    image: "/images/packages/holiday.webp",
  },
  {
    slug: "move-in-refresh",
    name: "Move-In Refresh Day",
    baseTimeHours: 4,
    basePriceMin: 299,
    basePriceMax: 499,
    outcome: "First day in: priority rooms usable and calm.",
    inclusions: [
      "Unpack priority rooms",
      "Break down boxes",
      "Essentials shopping",
      "Vendor coordination",
    ],
    limits: ["No heavy furniture moves", "No installation"],
    image: "/images/packages/move-in.webp",
  },
  {
    slug: "gift-concierge",
    name: "Gift Concierge",
    baseTimeHours: 2.5,
    basePriceMin: 129,
    basePriceMax: 249,
    outcome: "Never miss an occasion—plan, purchase, wrap, ship.",
    inclusions: ["Plan/purchase to brief", "Wrap/ship", "Reminder tracking"],
    limits: ["Purchases at cost (+10%)", "No high-value custody"],
    image: "/images/packages/gifts.webp",
  },
];

export const policies = {
  minCalloutHours: 2,
  addOnIncrementMinutes: 30,
  rushFee: 25,
  holidayFee: 40,
  mileageFreeMiles: 10,
  reimbursementHandlingPct: 10,
};
